hash-format = "sha256"

[[files]]
file = "config/paxi/datapacks/Big_Globe_V5.0.6_Create_V6.0.6.zip"
hash = "0f8e6d90f30677eb6b81116d9beb71a285430f316a49ef6444eb382c6ce06e86"

[[files]]
file = "config/paxi/datapacks/Big_Globe_V5.0.6_Tidal_Towns_V1.3.4.zip"
hash = "c0b42646ac4b689ff78dbe80fb22adb5f270ad8487cccc3d46b2381147b65ac1"

[[files]]
file = "config/paxi/datapacks/big-globe-compat-choicetheorems-overhauled-village.pw.toml"
hash = "3abd55fa9c04eb35afa5c9e59ffdb57ef211da73e74a2aed071968e7f15a5e15"
metafile = true

[[files]]
file = "config/paxi/datapacks/big-globe-compat-dungeons-and-taverns.pw.toml"
hash = "0a4769e1543bd313aa9221d1be9c2eebeeaee70a019dddcbdb6903130085b113"
metafile = true

[[files]]
file = "config/paxi/datapacks/big-globe-compat-hopo-better-underwater-ruins.pw.toml"
hash = "cb96537bdbb50dbdeaf88a637dccb87e2ee6fe4ace7abf2c8f8494cb2170f6af"
metafile = true

[[files]]
file = "config/paxi/datapacks/big-globe-compat-philips-ruins.pw.toml"
hash = "dc5ff79f664ba007baabaf7db787b8e8cfc35db37d329d86af0b950398ab515e"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/Big_Globe_retex_by_shes_long_1.2.zip"
hash = "1fb66db49b86b5530b2f6c54b8927d58316d6b5ba3f94fa20ee8fe2586d79c00"

[[files]]
file = "mods/amendments.pw.toml"
hash = "fb413ba504cfaae8ab4d96ede3944b8eb15fa4238ae02b4331bdad2549876f2e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/autohud.pw.toml"
hash = "1d39c4b2c4554ef1532b3f0d22e6a06d8750ce11acb2f51ba7d78868c7f4cdb7"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5ea9fb9ea7bf0fed99866d9dc20ffc907c6f6cf203dddeca9dda01ee475cfc37"
metafile = true

[[files]]
file = "mods/beautify.pw.toml"
hash = "5e3421b58c8c905e686ed7b63d2fe086fe3265009347ca01aba99f13cb8edca3"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "e1f4a53e3e52b534add5dd018597fefd345d9bd6350b9c46ef0ec281fc62af8e"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-modlist.pw.toml"
hash = "5ebc1849da4c78f57b8f4cde4320d5409ea9244e372d50afc6362ee88d66dd50"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "e1f1588b18947699ddc9b4f7c5b5406c5559155b8cb52dcd0f203c07c31cd0b8"
metafile = true

[[files]]
file = "mods/big-globe.pw.toml"
hash = "63c508a1f82d4c3f58dcb0b1ad758fcf0318df062262a438d28f6b2243df095b"
metafile = true

[[files]]
file = "mods/blocks-bogies.pw.toml"
hash = "66d6a153c156b11e472bb4c226bb3a88b519cac4cf306904f6308965b8fe5333"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "f80000f8a5c3e9abdb0d2a926fd67fd6191dcb1b710f0cdbf0ab26ec53b0a8bf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
hash = "e28f40d34c30c32d4bd05cfb80215c907b59e43d7e593ead73b3a04bb959bd4a"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "52e2cb54ee2933bf00e9b7886f47938a2dce1bf998293be2b38552083ffa5f9a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "c27af69a7c64206beff3e59c671934d4eb9a3dc65fd589609c5e6f6bb60421bb"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "bf463928645c586cb57a4e02533ee300af3931cf9db9233dae7efc1826643d41"
metafile = true

[[files]]
file = "mods/create-bitterballen.pw.toml"
hash = "bbe41c6629eca553fed13d7b3fee895a4d8008fc77d93cf12e3325e20ef2e3a6"
metafile = true

[[files]]
file = "mods/create-cheese.pw.toml"
hash = "c602d7f6d79303c84b333da9188415baee535a597b1cbfc0d52b701dab3935e0"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87ccbd409962ea48348bd005f00a7c68d2add8528cdc6287c83ff52d21dc8c98"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
hash = "bc4ef8bd7d32506703dcc175a62a12766addc393434ddbe8d17f01b071701943"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "485c1d97761536a52331e5d50055ecd514086e2f23937f259e33e06cc638ca91"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "7c07f70035a9ef0fa613bb1acab3db9377a7de11461761c4a33a52df71382c23"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "05995b86a58ee09106d8e34458a4eb7561ad5bf3e25d89f491519c18010afe8e"
metafile = true

[[files]]
file = "mods/create-sound-of-steam.pw.toml"
hash = "16a779fbdf47b154eb5ee30cc8ab41df3d3fe18308337824d66bd036c2c24014"
metafile = true

[[files]]
file = "mods/create-trimmed.pw.toml"
hash = "2e0e167422dc70f6d92da6669020e1cfd4417e47118ea66bd8f566a3295c8040"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "ac938235375a39bb489ab594baa553e88dd4805cbe1e03b377c83cadc4b3e3a5"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/dawn-of-time.pw.toml"
hash = "b80ba09f8b13a9678d734d6ebe3c009c61f12b316246e3341bd7a23a52c0bd47"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "632743d54d410c8b78fb92c94d8f3bb6a7a3faed45171f91e554877f94f82163"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "bbc15c019fd260bbb9058b14a8e03232a55df77608d9aca466d051007d62abd2"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
hash = "218dcd780f0251a15f78b097206ea22a519d57b974b39e2fdd43dce91ac07133"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "55d8b05d23120a823f9c25322722c47e6d30f18ecafce32c295cbf55b8d55ce0"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "b9244dca740d333c22f3425991fdd2fd40d3ae12384079a40a6fb7d4bca18a18"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "53b7e0bf344a566a16381c17c38fbf3c0c54ab2b5445dd90d3012eb3c191293e"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
hash = "11fe4ba3961ac419cd3f3d33d1ae660161ccb851878b922eb941b22e014649d0"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6b5fa0d3a684cf6cf33f1399c2b4bdbee34dbe362548808315b488ac172e2ada"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f48d8d1f04f68dc8e6cac4ed4768790fa7ab35ee23c2aaed5391d862c6043eab"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
hash = "e79856a2e2cee31d7d0c9476b87a7f3fa99ed05c863b3372dc12171cc2b6bdfd"
metafile = true

[[files]]
file = "mods/euphonium.pw.toml"
hash = "54d39131b07120334ad896779402eb5a372a1bcba5e089a50a17329fe3f29aee"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "f783b651d205662c70661f62f95cf30c7ec2ddd536970a04924663b7e8a18e88"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "2ac1df7fad83d36e69b4aaad32f0b952c9b039d7345592bb66934f40a8606224"
metafile = true

[[files]]
file = "mods/hopo-better-underwater-ruins.pw.toml"
hash = "be75fa97845b24c102d33441e3f1e9a24d0ab622d57b031c0d0f6888ce5927a5"
metafile = true

[[files]]
file = "mods/hypertube.pw.toml"
hash = "b87480679e8a340920cd02bc8113127a9039f35caf6361dd0e24f5190ea8b466"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
hash = "e821ee9757493ab64961588bad86d2292477fb2d1b1ce2f80ba9b246a55cec6d"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "9422e9e313d0ea266dffacf14d5bd55f9244d51d4f4587af7236cb778462461c"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/items-displayed-forge.pw.toml"
hash = "26d8d524c4e6ce464636fb22ea9c767ce4069ea1e786673df0c6efeda4a0d857"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "68e555e2c925017ccd7864862b30da4314a14b43db9b8b48fdf7546c1632495e"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "7905c08f37d8ebde50a5330a7dd10029de6259b0cb8adbde1170d93ea20218a7"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "52ad3f05b5a593f8f48371bcae785c4c4e328e0eb6c317e6942ce127878497e2"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "c6887c071d6515a39aeb915429304ea9fdae876decde3ad66062c9ba779b16b4"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "702df8b679041c5f459da5a0dc456f70de336810bc69ff726d8c925bf484e99c"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "494d362db9766b5cf594109dabc35c50d78c99699d68ebc87e0d6dd51e19c244"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "1d09669cac9fad91c06b914728f25b93aa4114cc61e336b3d03ff7025c849ebc"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "b5f1c37740051774214d8dd035df9bac68ddd4d8c71ed8949fdaabd5949829de"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "662593e017611512dfc07d2f3d8cdbc1e9c75c063bcc3921a959dd44dd23af6a"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "03e30fe65d594d7ff82782e190d14f383af98b1c15aef4dbdbcc44672d246c52"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "6e4155b4c0bdc2cbb051544db6a8253f95e8cae6f4e72a497d37ec39570f0a3d"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7713cc82e1ea68848508ed5c1a1c7bd1a832c0bcc97c96865891b9a2a33aa825"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "6afce08213c05a33240e980e2b92032a6a3ad25d2a54ff8e9f56b5f00d46d45d"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "f8080690eb60f050db45b1f3a1400c2b0ff5614912344a1ab9e8b80d3d2fa4dd"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "42805ef7e224873873d190b0363f2a53dae02530553574f29fab92e258bc0470"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "99813592c09351cb6340d8519d919e0d2d0b2f8073c3fe6833e7d846616bf5f2"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "3369ef3b2d68c6e54827e38e27d749444765b8da9be3202dc1139bba7f16a70b"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "44ac966d0108b74cd193af8ce3ba3358613a3ae362cce4ce82bf2c2d493482ff"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "215d597764d5c5db89e700fc3495b72dc0a7f09c975de19dc8c580bde3469a5e"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
hash = "2488bf19149e671ab9fc63823029b19ebae6c4eeabb7ff748c0be341758a246b"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "573f309a1bd1c410d149b6830aeddee7313e0698ac249a94f63a7e95c0eb146e"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "d735e9cc5652e654cfa85bd42c43b5f91d9ed96f008cdefe258f827dbda195c5"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "dee709ea8dbbb9e75de4d53b1b9e1fd0e535abc0809c1f5aaadf783178cccf21"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "625dcc2180c9c4cfe233ba192493bf2828e206f0d960c138281287d36ff61caf"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/satin-free-wakes.pw.toml"
hash = "da82584dc5c26adafb4df9b69fa2ed710ead914ce8384058665fcfa85950f5fa"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "2c1661e65d47c2942d2c3e926698d0762672224f1925c7f25105b964ce25b093"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "2507dd9242e994ec7a0b21255b0b51a91bf9e0e51b060defe7bf7f8fa1f04b53"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "dd29b00a0b7660bab0a04e066e8f796c5d5b89713d42a341493ca024d27796fd"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "09c393b303130cefffc1c376ddfdeb869b20db31d3d42d9fa155e13cfc628645"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "7ac912d80e0695b2bf3ee394f247f714df1dcd0df4975deb27487ea519ed8179"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "593fa7b30ab016aa45be07bd6bef3a9f160ed0f24689850d60bf84995d69b843"
metafile = true

[[files]]
file = "mods/stellarview.pw.toml"
hash = "3792d649d29e5c684218283dcb787cca922ac74524730ae04118768aaed5cccf"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "b8b217b7a7facbd986da814e609e01603ae5ac0ec996f746b8076c8ecd3d28fd"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "46d28a5f6168b55be612a6f5d616dd0a28bb33f8bf2c6b23c30c0bae17e8ae3c"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2e4c8891ec22ca246b414728493ff52fe177bc9c4369ed23a5a80e8332e79c67"
metafile = true

[[files]]
file = "mods/tidal-towns.pw.toml"
hash = "0ccb1c696758d7935d02dd5160987cab8d3594ab24f89deb01c28f9e596094e7"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "cfb56028963982b7c4714b3bc138cf7b2ccae9b1547143203770ccc4b6ef52e2"
metafile = true

[[files]]
file = "mods/vertigo.pw.toml"
hash = "6c22a27802b5ea349b8b1173f11c27354c19bf9dff27af5f6f4f8b75caedeb91"
metafile = true

[[files]]
file = "mods/visuality-forge.pw.toml"
hash = "e58928e10c503de8a82e8de066d7f17e96a1e67d7bc452386dac8695a48874fc"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "735bae0e4736022f33f59f85fae837549d19992b387fe38d92af613bbe101eea"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
hash = "a9c466cd6b58f1b584239cdce99f9a153507c4a51ceb7060399eb068600e1c3e"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "b844c10676b5911a4d2af32710d21fa22eafafcb6e1e3505fb8651b643cd99f7"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64eaf7478e42d5143f4feeee87c56f779f4c3523f9fb06d8342484d36aa4442b"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
hash = "5e25dccab496945a5f19bb82383e0ebf98452ffc14cd25c7e0259cc44312281a"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true

[[files]]
file = "resourcepacks/better-flame-particles.pw.toml"
hash = "ff85d06569c47f70c8fdd3ca44d80b3e19dff6e12e854a4bc8fd4ee09ec82940"
metafile = true

[[files]]
file = "resourcepacks/caelesti.pw.toml"
hash = "4d51468012511420ce3d8152d55cc21eaabcd5e2af1f90bdb6967ba4786e7f3a"
metafile = true

[[files]]
file = "resourcepacks/deep-origins-overlays.pw.toml"
hash = "fa21806ffb04232267b077cc193b6b59f66b76395b3f145d094ef5de9cf47bde"
metafile = true

[[files]]
file = "resourcepacks/deep-origins-snow-moss.pw.toml"
hash = "3581a35a6fa0b591fbd79b410d11f6e7d3e73709b3dd92b12f6dc3d595d58f8d"
metafile = true

[[files]]
file = "resourcepacks/deeper-mc.pw.toml"
hash = "a62a0163fda495a01883896acd9933333f3f6d9245b96d87f6566bb3e0231c61"
metafile = true

[[files]]
file = "resourcepacks/dimensionalized-3d-essentials.pw.toml"
hash = "24fe9b8f2848b7fe2bf74079d06afa87d768bc5817bfb3afa17744efd9e8b48f"
metafile = true

[[files]]
file = "resourcepacks/farm-3d.pw.toml"
hash = "ff1fe8a5fc848860ed02bf937d33dd8f7e2a51f6813709da37f8fe6f311c3751"
metafile = true

[[files]]
file = "resourcepacks/fire-rekindled.pw.toml"
hash = "fc3dd50981a9acfdcdd01efe8e6627f9cf22bdbeba5362791e3413ed8847dfce"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "8746720d6b24d22ba1c236235de5a02a8bdfc277abb6d6328aa152bca0895f82"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "resourcepacks/os-colorful-grasses.pw.toml"
hash = "558138f69712448e20cc3c8d72d4a749a175ce5c222913d4fbc009c5a3466651"
metafile = true

[[files]]
file = "resourcepacks/rekindled-ctm.pw.toml"
hash = "6ab9a33eadc5f00eab04d2177d2ffd7c119abc8ca593da3f7dad2ed9f8ce3946"
metafile = true

[[files]]
file = "resourcepacks/spbr.pw.toml"
hash = "1cc27f5b9dfe2a8cd3b8d43df0466b8086300e7cbd516785daf8910cee502f6e"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "32fe0fe8941110f8fba07ce7768faa1797de6b28e961ab65b483c380fc0a365a"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "f4fb7685cf5f1f07eb5b07b0dd7ea211e46e249cb3a78237358d27c3db1dea2b"
metafile = true

[[files]]
file = "shaderpacks/bloop-shaders.pw.toml"
hash = "96e2a8576f96c18fa78a0a6ca2d642663c7925b18579f0260ec67267272d73aa"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
