name = "Big Globe With Create"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b95e9e73e74d81495bc85b9c0f6d5fda7cc0a36701aa375840363c0c8a396ebb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "config/paxi/datapacks"
