name = "Big Globe With Create"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5eb8a8b1b406fd6222aca1cd3cfbcf8a5aa18d199230aa8890cdb029980ff3b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "config/paxi/datapacks"
